- name: Build sovereign rollup binary
  become: true
  become_user: sovereign
  shell: source /home/sovereign/.cargo/env && cargo build --release --bin {{rollup_bin}} --no-default-features --features {{da_feature}}
  args:
    chdir: /home/sovereign/{{repo_dir}}
    executable: /bin/bash