- name: Celestia authenticate
  become: true
  become_user: sovereign
  ansible.builtin.command:
    cmd: "celestia light auth admin --node.store /mnt/da --p2p.network {{p2p_network}}"
  register: command_output

- name: Render config with auth
  become: true
  become_user: sovereign
  ansible.builtin.template:
    src: "celestia_rollup_config.toml.j2"
    dest: "/home/sovereign/rollup_config.toml"
  vars:
    celestia_auth_token: "{{ command_output.stdout }}"

- name: Get key address from JSON output
  become: true
  become_user: sovereign
  ansible.builtin.command:
    cmd: "cel-key list --keyring-dir /mnt/da/keys/ --output json"
  register: key_list_output
  changed_when: false

- name: Parse JSON and extract address
  ansible.builtin.set_fact:
    key_address: "{{ (key_list_output.stdout | from_json)[0].address }}"

- name: Render sequencer config with address
  become: true
  become_user: sovereign
  ansible.builtin.template:
    src: "sequencer_registry.json.j2"
    dest: "{{genesis_folder}}/sequencer_registry.json"
  vars:
    sequencer_da_address: "{{ key_address }}"

- name: Replace sequencer address in Rust file
  become: true
  become_user: ubuntu
  ansible.builtin.replace:
    path: "/home/ubuntu/{{repo_dir}}/crates/rollup/src/celestia_rollup.rs"
    regexp: 'CelestiaAddress::from_str.*'
    replace: 'CelestiaAddress::from_str("{{ key_address }}")?;'
    backup: no
