- name: Checkout repo to
  become: true
  become_user: ubuntu
  git:
    repo: "git@github.com:/{{ org_name }}/{{ repo_name }}.git"
    dest: "/home/ubuntu/{{ repo_dir }}"
    version: "{{ commit_hash }}"
    accept_hostkey: yes
    force: yes
