---
commit_hash: "45c9ae0f4985b84eec1a8b6440a06aabfa2d231d"
rollup_config_path: /home/sovereign/{{repo_dir}}/celestia_rollup_config.toml
genesis_path: /home/sovereign/{{repo_dir}}/test-data/genesis/celestia
kernel_genesis_path: /home/sovereign/{{repo_dir}}/test-data/genesis/celestia/chain_state.json

