---
commit_hash: "6188c8aca7d73c7965871badfe3cb1174695374c"
sequencer_rollup_address: "sov1l6n2cku82yfqld30lanm2nfw43n2auc8clw7r5u5m6s7p8jrm4zqrr8r94"
rollup_namespace_prefix: "sov-roll01"
rollup_proof_namespace_prefix: "sov-prov01"
