- name: Set Go version variable
  set_fact:
    go_version: "1.21.1"

- name: Check if Go is installed
  become: true
  shell: go version
  environment:
    PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
  register: go_exists
  ignore_errors: yes

- name: Download Go tarball
  become: true
  get_url:
    url: "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    mode: '0755'
  when: go_exists is failed

- name: Remove existing Go installation
  become: true
  file:
    path: /usr/local/go
    state: absent
  when: go_exists is failed

- name: Extract Go tarball
  become: true
  unarchive:
    src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    creates: "/usr/local/go/bin/go"
    remote_src: yes
  when: go_exists is failed

- name: Remove Go tarball
  become: true
  file:
    path: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    state: absent
  when: go_exists is failed

- name: Ensure Go is available for the sovereign user
  lineinfile:
    path: /home/sovereign/.bashrc
    line: 'export PATH=$PATH:/usr/local/go/bin'
    create: yes
  become: true
  become_user: sovereign

