name: Rust

on:
  workflow_dispatch:
  push:
    branches: ["ibc-rollup"]
  pull_request:
    branches: ["ibc-rollup"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SOVEREIGN_SDK_PRIVATE_SSH_KEY }}
      - uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.SOVEREIGN_SDK_PRIVATE_SSH_KEY }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.2"
      - name: Install cargo-risczero
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-risczero@0.20
      - uses: taiki-e/install-action@nextest
      - name: Install risc0-zkvm toolchain # Use the risc0 cargo extension to install the risc0 std library for the current toolchain
        run: cargo risczero install --version v2024-04-22.0
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Check
        run: make lint
      - name: Run tests
        run: cargo nextest run
      - name: Run README.md
        run: chmod +x sov-rollup-starter.sh && ./sov-rollup-starter.sh
